services:
  - type: web
    name: lirkod-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: lirkod-db
          property: connectionString
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: FACEBOOK_APP_ID
        value: your-facebook-app-id
      - key: FACEBOOK_APP_SECRET
        value: your-facebook-app-secret
      - key: CORS_ORIGIN
        value: https://lirkod.vercel.app

databases:
  - name: lirkod-db
    plan: free
    databaseName: lirkod
    user: lirkod_user
